# yamllint disable rule:braces
# more information can be found here https://sonata-project.org/bundles/page
cmf_routing:
    chain:
        routers_by_id:
            # enable the DynamicRouter with high priority to allow overwriting configured routes with content
            #symfony_cmf_routing_extra.dynamic_router: 200
            # enable the symfony default router with a lower priority
            sonata.page.router: 150
            router.default: 100

sonata_page:
    slugify_service: 'sonata.page.slugify.cocur'
    class:
        site: App\Entity\Page\Site
        snapshot: App\Entity\Page\Snapshot
        page: App\Entity\Page\Page
        block: App\Entity\Page\Block

    multisite:             host # host_with_path
    use_streamed_response: false # set the value to false in debug mode or if the reverse proxy does not handle streamed response

    ignore_uri_patterns:
        - ^/admin(.*)
        - ^/api/(.*)

    ignore_route_patterns:
        - (.*)admin(.*)     # ignore admin route, ie route containing 'admin'
        - ^_(.*)            # ignore symfony routes

    ignore_routes:
        - sonata_page_cache_esi
        - sonata_page_cache_ssi
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc

    cache_invalidation:
        service: sonata.page.cache.invalidation.simple
        recorder: sonata.page.cache.recorder
        classes:
            Application\Sonata\PageBundle\Entity\Block: getId

    # use encore-webpack instead
    # do not remove this lines to avoid load default value
    assets:
        #stylesheets:
        #    - assetic/sonata_front_css.css

        #javascripts:
        #    - assetic/sonata_front_js.js

        stylesheets:
# RYL            - 'bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css'
# RYL            - 'bundles/sonatacore/vendor/select2/select2.css'
# RYL            - 'bundles/mopabootstrap/css/datepicker.css'
# RYL            - 'bundles/sonatademo/css/demo.css'
            - 'assets/app/app.css'
        javascripts:
# RYL            - 'bundles/sonataproduct/js/product.js'
# RYL            - 'bundles/sonatacore/js/base.js'
# RYL            - 'bundles/sonatademo/js/demo.js'
# RYL            - 'bundles/sonatapage/sonata-page.front.js'
# RYL            - 'bundles/sonatacore/vendor/jquery/dist/jquery.js'
# RYL            - 'bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.js'
# RYL            - 'bundles/sonatacore/vendor/select2/select2.min.js'
            - 'assets/app/app.js'
    default_template: portfoliomanager_default
    templates:
        'default':
            path: '@App/demo_layout.html.twig'
            name: 'default'
            containers:
                header:
                    name: Header
                    blocks:
                        - sonata.block.service.text
                content_top:
                    name: Top content
                content:
                    name: Main content
                content_bottom:
                    name: Bottom content
                footer:
                    name: Footer
            matrix:
                layout: |
                    HHHHHHHH
                    TTTTTTTT
                    CCCCCCCC
                    BBBBBBBB
                    FFFFFFFF

                mapping:
                    H: header
                    T: content_top
                    C: content
                    B: content_bottom
                    F: footer

        2columns:
            path: '@App/demo_2columns_layout.html.twig'
            name: '2 columns layout'
            containers:
                header:
                    name: Header
                content_top:
                    name: Top content
                left_col:
                    name: Left content
                right_col:
                    name: Right content
                content_bottom:
                    name: Bottom content
                footer:
                    name: Footer
            matrix:
                layout: |
                    HHHHHHHH
                    TTTTTTTT
                    LLLLRRRR
                    BBBBBBBB
                    FFFFFFFF

                mapping:
                    H: header
                    T: content_top
                    L: left_col
                    R: right_col
                    B: content_bottom
                    F: footer

        # RYL
        portfoliomanager_default:
            path: 'app_layout.html.twig'
            name: 'Portfolio Manager Standard'
            containers:
                 content_top:
                     name: Top content
                 content:
                     name: Main content
                 content_bottom:
                     name: Bottom content
            matrix:
                 layout: |
                     TTTTTTTT
                     CCCCCCCC
                     BBBBBBBB
                 mapping:
                     T: content_top
                     C: content
                     B: content_bottom

    page_defaults:
        homepage: { decorate: false, enabled: true }

    caches:
        esi:
            token: add an unique token here # default is a random value
            version: 3                        # version 3 is the default on debian wheezy ...
            servers:
                # you need to ajust this configuration to match your varnish configuration
                - '%sonata_page.varnish.command%'
        ssi:
            token: add an unique token here # default is a random value

    catch_exceptions:
        not_found: [404]    # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
        fatal: [500]    # so you can use the same page for different http errors or specify specific page for each error

# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataPageBundle: ~
