<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210605133723 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX IDX_ACF41FFEB96B5643');
        $this->addSql('CREATE TEMPORARY TABLE __temp__balance AS SELECT id, portfolio_id, currency, quantity FROM balance');
        $this->addSql('DROP TABLE balance');
        $this->addSql('CREATE TABLE balance (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, portfolio_id INTEGER NOT NULL, currency VARCHAR(3) NOT NULL COLLATE BINARY, quantity DOUBLE PRECISION DEFAULT NULL, CONSTRAINT FK_ACF41FFEB96B5643 FOREIGN KEY (portfolio_id) REFERENCES portfolio (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO balance (id, portfolio_id, currency, quantity) SELECT id, portfolio_id, currency, quantity FROM __temp__balance');
        $this->addSql('DROP TABLE __temp__balance');
        $this->addSql('CREATE INDEX IDX_ACF41FFEB96B5643 ON balance (portfolio_id)');
        $this->addSql('DROP INDEX IDX_43629B36727ACA70');
        $this->addSql('DROP INDEX IDX_43629B36E25D857E');
        $this->addSql('DROP INDEX IDX_43629B36EA9FDD75');
        $this->addSql('CREATE TEMPORARY TABLE __temp__classification__category AS SELECT id, parent_id, media_id, context, name, enabled, slug, description, position, created_at, updated_at FROM classification__category');
        $this->addSql('DROP TABLE classification__category');
        $this->addSql('CREATE TABLE classification__category (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, parent_id INTEGER DEFAULT NULL, media_id INTEGER DEFAULT NULL, context INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, enabled BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL COLLATE BINARY, description VARCHAR(255) DEFAULT NULL COLLATE BINARY, position INTEGER DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, CONSTRAINT FK_43629B36727ACA70 FOREIGN KEY (parent_id) REFERENCES classification__category (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_43629B36E25D857E FOREIGN KEY (context) REFERENCES classification__context (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_43629B36EA9FDD75 FOREIGN KEY (media_id) REFERENCES media__media (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO classification__category (id, parent_id, media_id, context, name, enabled, slug, description, position, created_at, updated_at) SELECT id, parent_id, media_id, context, name, enabled, slug, description, position, created_at, updated_at FROM __temp__classification__category');
        $this->addSql('DROP TABLE __temp__classification__category');
        $this->addSql('CREATE INDEX IDX_43629B36727ACA70 ON classification__category (parent_id)');
        $this->addSql('CREATE INDEX IDX_43629B36E25D857E ON classification__category (context)');
        $this->addSql('CREATE INDEX IDX_43629B36EA9FDD75 ON classification__category (media_id)');
        $this->addSql('DROP INDEX IDX_A406B56AE25D857E');
        $this->addSql('DROP INDEX IDX_A406B56AEA9FDD75');
        $this->addSql('DROP INDEX tag_collection');
        $this->addSql('CREATE TEMPORARY TABLE __temp__classification__collection AS SELECT id, media_id, context, name, enabled, slug, description, created_at, updated_at FROM classification__collection');
        $this->addSql('DROP TABLE classification__collection');
        $this->addSql('CREATE TABLE classification__collection (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, media_id INTEGER DEFAULT NULL, context INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, enabled BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL COLLATE BINARY, description VARCHAR(255) DEFAULT NULL COLLATE BINARY, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, CONSTRAINT FK_A406B56AE25D857E FOREIGN KEY (context) REFERENCES classification__context (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_A406B56AEA9FDD75 FOREIGN KEY (media_id) REFERENCES media__media (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO classification__collection (id, media_id, context, name, enabled, slug, description, created_at, updated_at) SELECT id, media_id, context, name, enabled, slug, description, created_at, updated_at FROM __temp__classification__collection');
        $this->addSql('DROP TABLE __temp__classification__collection');
        $this->addSql('CREATE INDEX IDX_A406B56AE25D857E ON classification__collection (context)');
        $this->addSql('CREATE INDEX IDX_A406B56AEA9FDD75 ON classification__collection (media_id)');
        $this->addSql('CREATE UNIQUE INDEX tag_collection ON classification__collection (slug, context)');
        $this->addSql('DROP INDEX IDX_CA57A1C7E25D857E');
        $this->addSql('DROP INDEX tag_context');
        $this->addSql('CREATE TEMPORARY TABLE __temp__classification__tag AS SELECT id, context, name, enabled, slug, created_at, updated_at FROM classification__tag');
        $this->addSql('DROP TABLE classification__tag');
        $this->addSql('CREATE TABLE classification__tag (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, context INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, enabled BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL COLLATE BINARY, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, CONSTRAINT FK_CA57A1C7E25D857E FOREIGN KEY (context) REFERENCES classification__context (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO classification__tag (id, context, name, enabled, slug, created_at, updated_at) SELECT id, context, name, enabled, slug, created_at, updated_at FROM __temp__classification__tag');
        $this->addSql('DROP TABLE __temp__classification__tag');
        $this->addSql('CREATE INDEX IDX_CA57A1C7E25D857E ON classification__tag (context)');
        $this->addSql('CREATE UNIQUE INDEX tag_context ON classification__tag (slug, context)');
        $this->addSql('DROP INDEX IDX_FD78D017E2904019');
        $this->addSql('DROP INDEX IDX_FD78D01712469DE2');
        $this->addSql('CREATE TEMPORARY TABLE __temp__comment__comment AS SELECT id, thread_id, category_id, body, ancestors, depth, created_at, state, author_name, email, website, note, private FROM comment__comment');
        $this->addSql('DROP TABLE comment__comment');
        $this->addSql('CREATE TABLE comment__comment (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, thread_id INTEGER DEFAULT NULL, category_id INTEGER DEFAULT NULL, body CLOB NOT NULL COLLATE BINARY, ancestors VARCHAR(1024) NOT NULL COLLATE BINARY, depth INTEGER NOT NULL, created_at DATETIME NOT NULL, state INTEGER NOT NULL, author_name VARCHAR(255) DEFAULT NULL COLLATE BINARY, email VARCHAR(255) DEFAULT NULL COLLATE BINARY, website VARCHAR(255) DEFAULT NULL COLLATE BINARY, note DOUBLE PRECISION DEFAULT NULL, private BOOLEAN DEFAULT NULL, CONSTRAINT FK_FD78D017E2904019 FOREIGN KEY (thread_id) REFERENCES comment__thread (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_FD78D01712469DE2 FOREIGN KEY (category_id) REFERENCES classification__category (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO comment__comment (id, thread_id, category_id, body, ancestors, depth, created_at, state, author_name, email, website, note, private) SELECT id, thread_id, category_id, body, ancestors, depth, created_at, state, author_name, email, website, note, private FROM __temp__comment__comment');
        $this->addSql('DROP TABLE __temp__comment__comment');
        $this->addSql('CREATE INDEX IDX_FD78D017E2904019 ON comment__comment (thread_id)');
        $this->addSql('CREATE INDEX IDX_FD78D01712469DE2 ON comment__comment (category_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__dividend AS SELECT id, country FROM dividend');
        $this->addSql('DROP TABLE dividend');
        $this->addSql('CREATE TABLE dividend (id INTEGER NOT NULL, country VARCHAR(2) NOT NULL COLLATE BINARY, PRIMARY KEY(id), CONSTRAINT FK_2D0D0909BF396750 FOREIGN KEY (id) REFERENCES statement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO dividend (id, country) SELECT id, country FROM __temp__dividend');
        $this->addSql('DROP TABLE __temp__dividend');
        $this->addSql('CREATE TEMPORARY TABLE __temp__fee_statement AS SELECT id FROM fee_statement');
        $this->addSql('DROP TABLE fee_statement');
        $this->addSql('CREATE TABLE fee_statement (id INTEGER NOT NULL, PRIMARY KEY(id), CONSTRAINT FK_5EDDFA7EBF396750 FOREIGN KEY (id) REFERENCES statement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO fee_statement (id) SELECT id FROM __temp__fee_statement');
        $this->addSql('DROP TABLE __temp__fee_statement');
        $this->addSql('DROP INDEX IDX_B3C77447A76ED395');
        $this->addSql('DROP INDEX IDX_B3C77447FE54D947');
        $this->addSql('CREATE TEMPORARY TABLE __temp__fos_user_user_group AS SELECT user_id, group_id FROM fos_user_user_group');
        $this->addSql('DROP TABLE fos_user_user_group');
        $this->addSql('CREATE TABLE fos_user_user_group (user_id INTEGER NOT NULL, group_id INTEGER NOT NULL, PRIMARY KEY(user_id, group_id), CONSTRAINT FK_B3C77447A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_B3C77447FE54D947 FOREIGN KEY (group_id) REFERENCES fos_user_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO fos_user_user_group (user_id, group_id) SELECT user_id, group_id FROM __temp__fos_user_user_group');
        $this->addSql('DROP TABLE __temp__fos_user_user_group');
        $this->addSql('CREATE INDEX IDX_B3C77447A76ED395 ON fos_user_user_group (user_id)');
        $this->addSql('CREATE INDEX IDX_B3C77447FE54D947 ON fos_user_user_group (group_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__interest_statement AS SELECT id FROM interest_statement');
        $this->addSql('DROP TABLE interest_statement');
        $this->addSql('CREATE TABLE interest_statement (id INTEGER NOT NULL, PRIMARY KEY(id), CONSTRAINT FK_5BC34053BF396750 FOREIGN KEY (id) REFERENCES statement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO interest_statement (id) SELECT id FROM __temp__interest_statement');
        $this->addSql('DROP TABLE __temp__interest_statement');
        $this->addSql('DROP INDEX IDX_80D4C5414E7AF8F');
        $this->addSql('DROP INDEX IDX_80D4C541EA9FDD75');
        $this->addSql('CREATE TEMPORARY TABLE __temp__media__gallery_media AS SELECT id, gallery_id, media_id, position, enabled, updated_at, created_at FROM media__gallery_media');
        $this->addSql('DROP TABLE media__gallery_media');
        $this->addSql('CREATE TABLE media__gallery_media (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, gallery_id INTEGER DEFAULT NULL, media_id INTEGER DEFAULT NULL, position INTEGER NOT NULL, enabled BOOLEAN NOT NULL, updated_at DATETIME NOT NULL, created_at DATETIME NOT NULL, CONSTRAINT FK_80D4C5414E7AF8F FOREIGN KEY (gallery_id) REFERENCES media__gallery (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_80D4C541EA9FDD75 FOREIGN KEY (media_id) REFERENCES media__media (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO media__gallery_media (id, gallery_id, media_id, position, enabled, updated_at, created_at) SELECT id, gallery_id, media_id, position, enabled, updated_at, created_at FROM __temp__media__gallery_media');
        $this->addSql('DROP TABLE __temp__media__gallery_media');
        $this->addSql('CREATE INDEX IDX_80D4C5414E7AF8F ON media__gallery_media (gallery_id)');
        $this->addSql('CREATE INDEX IDX_80D4C541EA9FDD75 ON media__gallery_media (media_id)');
        $this->addSql('DROP INDEX IDX_5C6DD74E12469DE2');
        $this->addSql('CREATE TEMPORARY TABLE __temp__media__media AS SELECT id, category_id, name, description, enabled, provider_name, provider_status, provider_reference, width, height, length, content_size, copyright, author_name, context, cdn_is_flushable, cdn_flush_at, cdn_status, updated_at, created_at, content_type, cdn_flush_identifier, provider_metadata FROM media__media');
        $this->addSql('DROP TABLE media__media');
        $this->addSql('CREATE TABLE media__media (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, category_id INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, description CLOB DEFAULT NULL COLLATE BINARY, enabled BOOLEAN NOT NULL, provider_name VARCHAR(255) NOT NULL COLLATE BINARY, provider_status INTEGER NOT NULL, provider_reference VARCHAR(255) NOT NULL COLLATE BINARY, width INTEGER DEFAULT NULL, height INTEGER DEFAULT NULL, length NUMERIC(10, 0) DEFAULT NULL, content_size INTEGER DEFAULT NULL, copyright VARCHAR(255) DEFAULT NULL COLLATE BINARY, author_name VARCHAR(255) DEFAULT NULL COLLATE BINARY, context VARCHAR(64) DEFAULT NULL COLLATE BINARY, cdn_is_flushable BOOLEAN DEFAULT NULL, cdn_flush_at DATETIME DEFAULT NULL, cdn_status INTEGER DEFAULT NULL, updated_at DATETIME NOT NULL, created_at DATETIME NOT NULL, content_type VARCHAR(255) DEFAULT NULL COLLATE BINARY, cdn_flush_identifier VARCHAR(64) DEFAULT NULL COLLATE BINARY, provider_metadata CLOB DEFAULT NULL COLLATE BINARY --(DC2Type:json)
        , CONSTRAINT FK_5C6DD74E12469DE2 FOREIGN KEY (category_id) REFERENCES classification__category (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO media__media (id, category_id, name, description, enabled, provider_name, provider_status, provider_reference, width, height, length, content_size, copyright, author_name, context, cdn_is_flushable, cdn_flush_at, cdn_status, updated_at, created_at, content_type, cdn_flush_identifier, provider_metadata) SELECT id, category_id, name, description, enabled, provider_name, provider_status, provider_reference, width, height, length, content_size, copyright, author_name, context, cdn_is_flushable, cdn_flush_at, cdn_status, updated_at, created_at, content_type, cdn_flush_identifier, provider_metadata FROM __temp__media__media');
        $this->addSql('DROP TABLE __temp__media__media');
        $this->addSql('CREATE INDEX IDX_5C6DD74E12469DE2 ON media__media (category_id)');
        $this->addSql('DROP INDEX IDX_A90210404B89032C');
        $this->addSql('CREATE TEMPORARY TABLE __temp__news__comment AS SELECT id, post_id, name, url, email, message, status, created_at, updated_at FROM news__comment');
        $this->addSql('DROP TABLE news__comment');
        $this->addSql('CREATE TABLE news__comment (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, post_id INTEGER NOT NULL, name VARCHAR(255) DEFAULT NULL COLLATE BINARY, url VARCHAR(255) DEFAULT NULL COLLATE BINARY, email VARCHAR(255) DEFAULT NULL COLLATE BINARY, message CLOB NOT NULL COLLATE BINARY, status INTEGER NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, CONSTRAINT FK_A90210404B89032C FOREIGN KEY (post_id) REFERENCES news__post (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO news__comment (id, post_id, name, url, email, message, status, created_at, updated_at) SELECT id, post_id, name, url, email, message, status, created_at, updated_at FROM __temp__news__comment');
        $this->addSql('DROP TABLE __temp__news__comment');
        $this->addSql('CREATE INDEX IDX_A90210404B89032C ON news__comment (post_id)');
        $this->addSql('DROP INDEX IDX_7D109BC83DA5256D');
        $this->addSql('DROP INDEX IDX_7D109BC8514956FD');
        $this->addSql('DROP INDEX IDX_7D109BC8F675F31B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__news__post AS SELECT id, image_id, author_id, collection_id, title, abstract, content, raw_content, content_formatter, enabled, slug, publication_date_start, comments_enabled, comments_close_at, comments_default_status, comments_count, created_at, updated_at FROM news__post');
        $this->addSql('DROP TABLE news__post');
        $this->addSql('CREATE TABLE news__post (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, image_id INTEGER DEFAULT NULL, author_id INTEGER DEFAULT NULL, collection_id INTEGER DEFAULT NULL, title VARCHAR(255) NOT NULL COLLATE BINARY, abstract CLOB NOT NULL COLLATE BINARY, content CLOB NOT NULL COLLATE BINARY, raw_content CLOB NOT NULL COLLATE BINARY, content_formatter VARCHAR(255) NOT NULL COLLATE BINARY, enabled BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL COLLATE BINARY, publication_date_start DATETIME DEFAULT NULL, comments_enabled BOOLEAN NOT NULL, comments_close_at DATETIME DEFAULT NULL, comments_default_status INTEGER NOT NULL, comments_count INTEGER DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, CONSTRAINT FK_7D109BC83DA5256D FOREIGN KEY (image_id) REFERENCES media__media (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_7D109BC8F675F31B FOREIGN KEY (author_id) REFERENCES fos_user_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_7D109BC8514956FD FOREIGN KEY (collection_id) REFERENCES classification__collection (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO news__post (id, image_id, author_id, collection_id, title, abstract, content, raw_content, content_formatter, enabled, slug, publication_date_start, comments_enabled, comments_close_at, comments_default_status, comments_count, created_at, updated_at) SELECT id, image_id, author_id, collection_id, title, abstract, content, raw_content, content_formatter, enabled, slug, publication_date_start, comments_enabled, comments_close_at, comments_default_status, comments_count, created_at, updated_at FROM __temp__news__post');
        $this->addSql('DROP TABLE __temp__news__post');
        $this->addSql('CREATE INDEX IDX_7D109BC83DA5256D ON news__post (image_id)');
        $this->addSql('CREATE INDEX IDX_7D109BC8514956FD ON news__post (collection_id)');
        $this->addSql('CREATE INDEX IDX_7D109BC8F675F31B ON news__post (author_id)');
        $this->addSql('DROP INDEX IDX_682B20514B89032C');
        $this->addSql('DROP INDEX IDX_682B2051BAD26311');
        $this->addSql('CREATE TEMPORARY TABLE __temp__news__post_tag AS SELECT post_id, tag_id FROM news__post_tag');
        $this->addSql('DROP TABLE news__post_tag');
        $this->addSql('CREATE TABLE news__post_tag (post_id INTEGER NOT NULL, tag_id INTEGER NOT NULL, PRIMARY KEY(post_id, tag_id), CONSTRAINT FK_682B20514B89032C FOREIGN KEY (post_id) REFERENCES news__post (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_682B2051BAD26311 FOREIGN KEY (tag_id) REFERENCES classification__tag (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO news__post_tag (post_id, tag_id) SELECT post_id, tag_id FROM __temp__news__post_tag');
        $this->addSql('DROP TABLE __temp__news__post_tag');
        $this->addSql('CREATE INDEX IDX_682B20514B89032C ON news__post_tag (post_id)');
        $this->addSql('CREATE INDEX IDX_682B2051BAD26311 ON news__post_tag (tag_id)');
        $this->addSql('DROP INDEX IDX_BE94B39E9B6B5FBA');
        $this->addSql('DROP INDEX IDX_BE94B39E2576E0FD');
        $this->addSql('CREATE TEMPORARY TABLE __temp__open_order AS SELECT id, account_id, contract_id, perm_id, client_id, order_id, action_type, total_qty, cash_qty, lmt_price, aux_price, status, remaining_qty FROM open_order');
        $this->addSql('DROP TABLE open_order');
        $this->addSql('CREATE TABLE open_order (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, account_id INTEGER NOT NULL, contract_id INTEGER NOT NULL, perm_id INTEGER NOT NULL, client_id INTEGER NOT NULL, order_id INTEGER NOT NULL, action_type VARCHAR(4) NOT NULL COLLATE BINARY, total_qty DOUBLE PRECISION DEFAULT NULL, cash_qty DOUBLE PRECISION DEFAULT NULL, lmt_price DOUBLE PRECISION DEFAULT NULL, aux_price DOUBLE PRECISION DEFAULT NULL, status VARCHAR(16) NOT NULL COLLATE BINARY, remaining_qty DOUBLE PRECISION NOT NULL, CONSTRAINT FK_BE94B39E9B6B5FBA FOREIGN KEY (account_id) REFERENCES portfolio (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_BE94B39E2576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO open_order (id, account_id, contract_id, perm_id, client_id, order_id, action_type, total_qty, cash_qty, lmt_price, aux_price, status, remaining_qty) SELECT id, account_id, contract_id, perm_id, client_id, order_id, action_type, total_qty, cash_qty, lmt_price, aux_price, status, remaining_qty FROM __temp__open_order');
        $this->addSql('DROP TABLE __temp__open_order');
        $this->addSql('CREATE INDEX IDX_BE94B39E9B6B5FBA ON open_order (account_id)');
        $this->addSql('CREATE INDEX IDX_BE94B39E2576E0FD ON open_order (contract_id)');
        $this->addSql('DROP INDEX IDX_5A8600B0DCD6110');
        $this->addSql('CREATE TEMPORARY TABLE __temp__option AS SELECT id, stock_id, call_or_put, strike, last_trade_date, multiplier, implied_volatility, delta, pv_dividend, gamma, vega, theta FROM option');
        $this->addSql('DROP TABLE option');
        $this->addSql('CREATE TABLE option (id INTEGER NOT NULL, stock_id INTEGER NOT NULL, call_or_put VARCHAR(1) NOT NULL COLLATE BINARY, strike DOUBLE PRECISION NOT NULL, last_trade_date DATE NOT NULL, multiplier INTEGER NOT NULL, implied_volatility DOUBLE PRECISION DEFAULT NULL, delta DOUBLE PRECISION DEFAULT NULL, pv_dividend DOUBLE PRECISION DEFAULT NULL, gamma DOUBLE PRECISION DEFAULT NULL, vega DOUBLE PRECISION DEFAULT NULL, theta DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id), CONSTRAINT FK_5A8600B0DCD6110 FOREIGN KEY (stock_id) REFERENCES stock (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_5A8600B0BF396750 FOREIGN KEY (id) REFERENCES contract (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO option (id, stock_id, call_or_put, strike, last_trade_date, multiplier, implied_volatility, delta, pv_dividend, gamma, vega, theta) SELECT id, stock_id, call_or_put, strike, last_trade_date, multiplier, implied_volatility, delta, pv_dividend, gamma, vega, theta FROM __temp__option');
        $this->addSql('DROP TABLE __temp__option');
        $this->addSql('CREATE INDEX IDX_5A8600B0DCD6110 ON option (stock_id)');
        $this->addSql('DROP INDEX IDX_66F58DA0727ACA70');
        $this->addSql('DROP INDEX IDX_66F58DA0C4663E4');
        $this->addSql('CREATE TEMPORARY TABLE __temp__page__block AS SELECT id, parent_id, page_id, name, enabled, position, created_at, updated_at, type, settings FROM page__block');
        $this->addSql('DROP TABLE page__block');
        $this->addSql('CREATE TABLE page__block (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, parent_id INTEGER DEFAULT NULL, page_id INTEGER DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE BINARY, enabled BOOLEAN DEFAULT NULL, position INTEGER DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, type VARCHAR(255) NOT NULL COLLATE BINARY, settings CLOB NOT NULL COLLATE BINARY --(DC2Type:json)
        , CONSTRAINT FK_66F58DA0727ACA70 FOREIGN KEY (parent_id) REFERENCES page__block (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_66F58DA0C4663E4 FOREIGN KEY (page_id) REFERENCES page__page (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO page__block (id, parent_id, page_id, name, enabled, position, created_at, updated_at, type, settings) SELECT id, parent_id, page_id, name, enabled, position, created_at, updated_at, type, settings FROM __temp__page__block');
        $this->addSql('DROP TABLE __temp__page__block');
        $this->addSql('CREATE INDEX IDX_66F58DA0727ACA70 ON page__block (parent_id)');
        $this->addSql('CREATE INDEX IDX_66F58DA0C4663E4 ON page__block (page_id)');
        $this->addSql('DROP INDEX IDX_2FAE39EDF6BD1646');
        $this->addSql('DROP INDEX IDX_2FAE39ED727ACA70');
        $this->addSql('DROP INDEX IDX_2FAE39ED158E0B66');
        $this->addSql('CREATE TEMPORARY TABLE __temp__page__page AS SELECT id, site_id, parent_id, target_id, route_name, page_alias, type, position, enabled, decorate, edited, name, slug, url, custom_url, request_method, title, meta_keyword, meta_description, javascript, stylesheet, raw_headers, template, created_at, updated_at FROM page__page');
        $this->addSql('DROP TABLE page__page');
        $this->addSql('CREATE TABLE page__page (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, site_id INTEGER DEFAULT NULL, parent_id INTEGER DEFAULT NULL, target_id INTEGER DEFAULT NULL, route_name VARCHAR(255) NOT NULL COLLATE BINARY, page_alias VARCHAR(255) DEFAULT NULL COLLATE BINARY, type VARCHAR(255) DEFAULT NULL COLLATE BINARY, position INTEGER NOT NULL, enabled BOOLEAN NOT NULL, decorate BOOLEAN NOT NULL, edited BOOLEAN NOT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, slug CLOB DEFAULT NULL COLLATE BINARY, url CLOB DEFAULT NULL COLLATE BINARY, custom_url CLOB DEFAULT NULL COLLATE BINARY, request_method VARCHAR(255) DEFAULT NULL COLLATE BINARY, title VARCHAR(255) DEFAULT NULL COLLATE BINARY, meta_keyword VARCHAR(255) DEFAULT NULL COLLATE BINARY, meta_description VARCHAR(255) DEFAULT NULL COLLATE BINARY, javascript CLOB DEFAULT NULL COLLATE BINARY, stylesheet CLOB DEFAULT NULL COLLATE BINARY, raw_headers CLOB DEFAULT NULL COLLATE BINARY, template VARCHAR(255) NOT NULL COLLATE BINARY, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, CONSTRAINT FK_2FAE39EDF6BD1646 FOREIGN KEY (site_id) REFERENCES page__site (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_2FAE39ED727ACA70 FOREIGN KEY (parent_id) REFERENCES page__page (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_2FAE39ED158E0B66 FOREIGN KEY (target_id) REFERENCES page__page (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO page__page (id, site_id, parent_id, target_id, route_name, page_alias, type, position, enabled, decorate, edited, name, slug, url, custom_url, request_method, title, meta_keyword, meta_description, javascript, stylesheet, raw_headers, template, created_at, updated_at) SELECT id, site_id, parent_id, target_id, route_name, page_alias, type, position, enabled, decorate, edited, name, slug, url, custom_url, request_method, title, meta_keyword, meta_description, javascript, stylesheet, raw_headers, template, created_at, updated_at FROM __temp__page__page');
        $this->addSql('DROP TABLE __temp__page__page');
        $this->addSql('CREATE INDEX IDX_2FAE39EDF6BD1646 ON page__page (site_id)');
        $this->addSql('CREATE INDEX IDX_2FAE39ED727ACA70 ON page__page (parent_id)');
        $this->addSql('CREATE INDEX IDX_2FAE39ED158E0B66 ON page__page (target_id)');
        $this->addSql('DROP INDEX IDX_3963EF9AF6BD1646');
        $this->addSql('DROP INDEX IDX_3963EF9AC4663E4');
        $this->addSql('DROP INDEX idx_snapshot_dates_enabled');
        $this->addSql('CREATE TEMPORARY TABLE __temp__page__snapshot AS SELECT id, site_id, page_id, route_name, page_alias, type, position, enabled, decorate, name, url, parent_id, target_id, publication_date_start, publication_date_end, created_at, updated_at, content FROM page__snapshot');
        $this->addSql('DROP TABLE page__snapshot');
        $this->addSql('CREATE TABLE page__snapshot (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, site_id INTEGER DEFAULT NULL, page_id INTEGER DEFAULT NULL, route_name VARCHAR(255) NOT NULL COLLATE BINARY, page_alias VARCHAR(255) DEFAULT NULL COLLATE BINARY, type VARCHAR(255) DEFAULT NULL COLLATE BINARY, position INTEGER NOT NULL, enabled BOOLEAN NOT NULL, decorate BOOLEAN NOT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, url CLOB DEFAULT NULL COLLATE BINARY, parent_id INTEGER DEFAULT NULL, target_id INTEGER DEFAULT NULL, publication_date_start DATETIME DEFAULT NULL, publication_date_end DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, content CLOB DEFAULT NULL COLLATE BINARY --(DC2Type:json)
        , CONSTRAINT FK_3963EF9AF6BD1646 FOREIGN KEY (site_id) REFERENCES page__site (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_3963EF9AC4663E4 FOREIGN KEY (page_id) REFERENCES page__page (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO page__snapshot (id, site_id, page_id, route_name, page_alias, type, position, enabled, decorate, name, url, parent_id, target_id, publication_date_start, publication_date_end, created_at, updated_at, content) SELECT id, site_id, page_id, route_name, page_alias, type, position, enabled, decorate, name, url, parent_id, target_id, publication_date_start, publication_date_end, created_at, updated_at, content FROM __temp__page__snapshot');
        $this->addSql('DROP TABLE __temp__page__snapshot');
        $this->addSql('CREATE INDEX IDX_3963EF9AF6BD1646 ON page__snapshot (site_id)');
        $this->addSql('CREATE INDEX IDX_3963EF9AC4663E4 ON page__snapshot (page_id)');
        $this->addSql('CREATE INDEX idx_snapshot_dates_enabled ON page__snapshot (publication_date_start, publication_date_end, enabled)');
        $this->addSql('DROP INDEX IDX_A9ED10627E3C61F9');
        $this->addSql('DROP INDEX IDX_A9ED1062E80D127B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__portfolio AS SELECT id, owner_id, benchmark_id, account, base_currency, name, put_ratio, sell_naked_put_sleep, find_symbols_sleep FROM portfolio');
        $this->addSql('DROP TABLE portfolio');
        $this->addSql('CREATE TABLE portfolio (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, owner_id INTEGER DEFAULT NULL, benchmark_id INTEGER DEFAULT NULL, account VARCHAR(31) NOT NULL COLLATE BINARY, base_currency VARCHAR(3) NOT NULL COLLATE BINARY, name VARCHAR(32) DEFAULT NULL COLLATE BINARY, put_ratio DOUBLE PRECISION DEFAULT NULL, sell_naked_put_sleep SMALLINT DEFAULT NULL, find_symbols_sleep SMALLINT DEFAULT NULL, adjust_cash_sleep SMALLINT DEFAULT NULL, CONSTRAINT FK_A9ED10627E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_A9ED1062E80D127B FOREIGN KEY (benchmark_id) REFERENCES stock (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO portfolio (id, owner_id, benchmark_id, account, base_currency, name, put_ratio, sell_naked_put_sleep, find_symbols_sleep) SELECT id, owner_id, benchmark_id, account, base_currency, name, put_ratio, sell_naked_put_sleep, find_symbols_sleep FROM __temp__portfolio');
        $this->addSql('DROP TABLE __temp__portfolio');
        $this->addSql('CREATE INDEX IDX_A9ED10627E3C61F9 ON portfolio (owner_id)');
        $this->addSql('CREATE INDEX IDX_A9ED1062E80D127B ON portfolio (benchmark_id)');
        $this->addSql('DROP INDEX IDX_462CE4F52576E0FD');
        $this->addSql('DROP INDEX IDX_462CE4F5B96B5643');
        $this->addSql('CREATE TEMPORARY TABLE __temp__position AS SELECT id, contract_id, portfolio_id, cost, open_date, quantity FROM position');
        $this->addSql('DROP TABLE position');
        $this->addSql('CREATE TABLE position (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, contract_id INTEGER NOT NULL, portfolio_id INTEGER DEFAULT NULL, cost DOUBLE PRECISION DEFAULT NULL, open_date DATE NOT NULL, quantity DOUBLE PRECISION NOT NULL, CONSTRAINT FK_462CE4F5B96B5643 FOREIGN KEY (portfolio_id) REFERENCES portfolio (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_462CE4F52576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO position (id, contract_id, portfolio_id, cost, open_date, quantity) SELECT id, contract_id, portfolio_id, cost, open_date, quantity FROM __temp__position');
        $this->addSql('DROP TABLE __temp__position');
        $this->addSql('CREATE INDEX IDX_462CE4F52576E0FD ON position (contract_id)');
        $this->addSql('CREATE INDEX IDX_462CE4F5B96B5643 ON position (portfolio_id)');
        $this->addSql('DROP INDEX IDX_C0DB5176B96B5643');
        $this->addSql('DROP INDEX IDX_C0DB5176DCD6110');
        $this->addSql('DROP INDEX IDX_C0DB5176B3D28FB');
        $this->addSql('CREATE TEMPORARY TABLE __temp__statement AS SELECT id, portfolio_id, stock_id, trade_unit_id, statement_type, date, currency, description, amount, trade_id, fx_rate_to_base FROM statement');
        $this->addSql('DROP TABLE statement');
        $this->addSql('CREATE TABLE statement (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, portfolio_id INTEGER NOT NULL, stock_id INTEGER DEFAULT NULL, trade_unit_id INTEGER DEFAULT NULL, statement_type VARCHAR(4) NOT NULL COLLATE BINARY, date DATETIME NOT NULL, currency VARCHAR(3) NOT NULL COLLATE BINARY, description VARCHAR(64) DEFAULT NULL COLLATE BINARY, amount DOUBLE PRECISION NOT NULL, trade_id INTEGER DEFAULT NULL, fx_rate_to_base DOUBLE PRECISION DEFAULT NULL, CONSTRAINT FK_C0DB5176B96B5643 FOREIGN KEY (portfolio_id) REFERENCES portfolio (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C0DB5176DCD6110 FOREIGN KEY (stock_id) REFERENCES stock (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C0DB5176B3D28FB FOREIGN KEY (trade_unit_id) REFERENCES trade_unit (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO statement (id, portfolio_id, stock_id, trade_unit_id, statement_type, date, currency, description, amount, trade_id, fx_rate_to_base) SELECT id, portfolio_id, stock_id, trade_unit_id, statement_type, date, currency, description, amount, trade_id, fx_rate_to_base FROM __temp__statement');
        $this->addSql('DROP TABLE __temp__statement');
        $this->addSql('CREATE INDEX IDX_C0DB5176B96B5643 ON statement (portfolio_id)');
        $this->addSql('CREATE INDEX IDX_C0DB5176DCD6110 ON statement (stock_id)');
        $this->addSql('CREATE INDEX IDX_C0DB5176B3D28FB ON statement (trade_unit_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__stock AS SELECT id, dividend_ttm, eps_ttm, eps_forward, description, industry, category, historical_volatility, subcategory FROM stock');
        $this->addSql('DROP TABLE stock');
        $this->addSql('CREATE TABLE stock (id INTEGER NOT NULL, dividend_ttm DOUBLE PRECISION DEFAULT NULL, eps_ttm DOUBLE PRECISION DEFAULT NULL, eps_forward DOUBLE PRECISION DEFAULT NULL, description VARCHAR(31) DEFAULT NULL COLLATE BINARY, industry VARCHAR(32) DEFAULT NULL COLLATE BINARY, category VARCHAR(32) DEFAULT NULL COLLATE BINARY, historical_volatility DOUBLE PRECISION DEFAULT NULL, subcategory VARCHAR(40) DEFAULT NULL COLLATE BINARY, PRIMARY KEY(id), CONSTRAINT FK_4B365660BF396750 FOREIGN KEY (id) REFERENCES contract (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO stock (id, dividend_ttm, eps_ttm, eps_forward, description, industry, category, historical_volatility, subcategory) SELECT id, dividend_ttm, eps_ttm, eps_forward, description, industry, category, historical_volatility, subcategory FROM __temp__stock');
        $this->addSql('DROP TABLE __temp__stock');
        $this->addSql('CREATE TEMPORARY TABLE __temp__tax AS SELECT id, country FROM tax');
        $this->addSql('DROP TABLE tax');
        $this->addSql('CREATE TABLE tax (id INTEGER NOT NULL, country VARCHAR(2) NOT NULL COLLATE BINARY, PRIMARY KEY(id), CONSTRAINT FK_8E81BA76BF396750 FOREIGN KEY (id) REFERENCES statement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO tax (id, country) SELECT id, country FROM __temp__tax');
        $this->addSql('DROP TABLE __temp__tax');
        $this->addSql('CREATE TEMPORARY TABLE __temp__trade AS SELECT id, price, quantity, proceeds, fees, realized_pnl, status FROM trade');
        $this->addSql('DROP TABLE trade');
        $this->addSql('CREATE TABLE trade (id INTEGER NOT NULL, price DOUBLE PRECISION NOT NULL, quantity DOUBLE PRECISION NOT NULL, proceeds DOUBLE PRECISION DEFAULT NULL, fees DOUBLE PRECISION DEFAULT NULL, realized_pnl DOUBLE PRECISION DEFAULT NULL, status SMALLINT NOT NULL, PRIMARY KEY(id), CONSTRAINT FK_7E1A4366BF396750 FOREIGN KEY (id) REFERENCES statement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO trade (id, price, quantity, proceeds, fees, realized_pnl, status) SELECT id, price, quantity, proceeds, fees, realized_pnl, status FROM __temp__trade');
        $this->addSql('DROP TABLE __temp__trade');
        $this->addSql('DROP INDEX IDX_63AFBEA22576E0FD');
        $this->addSql('CREATE TEMPORARY TABLE __temp__trade_option AS SELECT id, contract_id, proceeds, fees, quantity, realized_pnl, price, status FROM trade_option');
        $this->addSql('DROP TABLE trade_option');
        $this->addSql('CREATE TABLE trade_option (id INTEGER NOT NULL, contract_id INTEGER NOT NULL, proceeds DOUBLE PRECISION DEFAULT NULL, fees DOUBLE PRECISION DEFAULT NULL, quantity DOUBLE PRECISION NOT NULL, realized_pnl DOUBLE PRECISION DEFAULT NULL, price DOUBLE PRECISION NOT NULL, status SMALLINT NOT NULL, PRIMARY KEY(id), CONSTRAINT FK_63AFBEA22576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_63AFBEA2BF396750 FOREIGN KEY (id) REFERENCES statement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO trade_option (id, contract_id, proceeds, fees, quantity, realized_pnl, price, status) SELECT id, contract_id, proceeds, fees, quantity, realized_pnl, price, status FROM __temp__trade_option');
        $this->addSql('DROP TABLE __temp__trade_option');
        $this->addSql('CREATE INDEX IDX_63AFBEA22576E0FD ON trade_option (contract_id)');
        $this->addSql('DROP INDEX IDX_BE407BA8B96B5643');
        $this->addSql('DROP INDEX IDX_BE407BA8C0F75674');
        $this->addSql('CREATE TEMPORARY TABLE __temp__trade_unit AS SELECT id, symbol_id, portfolio_id, strategy, closing_date, status, pn_l, currency, opening_date, risk, comment FROM trade_unit');
        $this->addSql('DROP TABLE trade_unit');
        $this->addSql('CREATE TABLE trade_unit (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, symbol_id INTEGER NOT NULL, portfolio_id INTEGER DEFAULT NULL, strategy SMALLINT NOT NULL, closing_date DATETIME DEFAULT NULL, status SMALLINT NOT NULL, pn_l DOUBLE PRECISION DEFAULT NULL, currency VARCHAR(3) DEFAULT NULL COLLATE BINARY, opening_date DATETIME DEFAULT NULL, risk INTEGER DEFAULT NULL, comment VARCHAR(255) DEFAULT NULL COLLATE BINARY, CONSTRAINT FK_BE407BA8C0F75674 FOREIGN KEY (symbol_id) REFERENCES stock (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_BE407BA8B96B5643 FOREIGN KEY (portfolio_id) REFERENCES portfolio (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO trade_unit (id, symbol_id, portfolio_id, strategy, closing_date, status, pn_l, currency, opening_date, risk, comment) SELECT id, symbol_id, portfolio_id, strategy, closing_date, status, pn_l, currency, opening_date, risk, comment FROM __temp__trade_unit');
        $this->addSql('DROP TABLE __temp__trade_unit');
        $this->addSql('CREATE INDEX IDX_BE407BA8B96B5643 ON trade_unit (portfolio_id)');
        $this->addSql('CREATE INDEX IDX_BE407BA8C0F75674 ON trade_unit (symbol_id)');
        $this->addSql('DROP INDEX IDX_CE33C44BB96B5643');
        $this->addSql('DROP INDEX IDX_CE33C44BDCD6110');
        $this->addSql('CREATE TEMPORARY TABLE __temp__trading_parameters AS SELECT id, stock_id, portfolio_id, nav_ratio FROM trading_parameters');
        $this->addSql('DROP TABLE trading_parameters');
        $this->addSql('CREATE TABLE trading_parameters (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, stock_id INTEGER NOT NULL, portfolio_id INTEGER NOT NULL, nav_ratio DOUBLE PRECISION NOT NULL, CONSTRAINT FK_CE33C44BDCD6110 FOREIGN KEY (stock_id) REFERENCES stock (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_CE33C44BB96B5643 FOREIGN KEY (portfolio_id) REFERENCES portfolio (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO trading_parameters (id, stock_id, portfolio_id, nav_ratio) SELECT id, stock_id, portfolio_id, nav_ratio FROM __temp__trading_parameters');
        $this->addSql('DROP TABLE __temp__trading_parameters');
        $this->addSql('CREATE INDEX IDX_CE33C44BB96B5643 ON trading_parameters (portfolio_id)');
        $this->addSql('CREATE INDEX IDX_CE33C44BDCD6110 ON trading_parameters (stock_id)');
        $this->addSql('DROP INDEX IDX_9407E54977FA751A');
        $this->addSql('DROP INDEX UNIQ_9407E5494B12AD6EA000B10');
        $this->addSql('CREATE TEMPORARY TABLE __temp__acl_object_identities AS SELECT id, parent_object_identity_id, object_identifier, entries_inheriting, class_id FROM acl_object_identities');
        $this->addSql('DROP TABLE acl_object_identities');
        $this->addSql('CREATE TABLE acl_object_identities (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, parent_object_identity_id INTEGER UNSIGNED DEFAULT NULL, object_identifier VARCHAR(100) NOT NULL COLLATE BINARY, entries_inheriting BOOLEAN NOT NULL, class_id INTEGER UNSIGNED NOT NULL, CONSTRAINT FK_9407E54977FA751A FOREIGN KEY (parent_object_identity_id) REFERENCES acl_object_identities (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO acl_object_identities (id, parent_object_identity_id, object_identifier, entries_inheriting, class_id) SELECT id, parent_object_identity_id, object_identifier, entries_inheriting, class_id FROM __temp__acl_object_identities');
        $this->addSql('DROP TABLE __temp__acl_object_identities');
        $this->addSql('CREATE INDEX IDX_9407E54977FA751A ON acl_object_identities (parent_object_identity_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9407E5494B12AD6EA000B10 ON acl_object_identities (object_identifier, class_id)');
        $this->addSql('DROP INDEX IDX_825DE2993D9AB4A6');
        $this->addSql('DROP INDEX IDX_825DE299C671CEA1');
        $this->addSql('CREATE TEMPORARY TABLE __temp__acl_object_identity_ancestors AS SELECT object_identity_id, ancestor_id FROM acl_object_identity_ancestors');
        $this->addSql('DROP TABLE acl_object_identity_ancestors');
        $this->addSql('CREATE TABLE acl_object_identity_ancestors (object_identity_id INTEGER UNSIGNED NOT NULL, ancestor_id INTEGER UNSIGNED NOT NULL, PRIMARY KEY(object_identity_id, ancestor_id), CONSTRAINT FK_825DE2993D9AB4A6 FOREIGN KEY (object_identity_id) REFERENCES acl_object_identities (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_825DE299C671CEA1 FOREIGN KEY (ancestor_id) REFERENCES acl_object_identities (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO acl_object_identity_ancestors (object_identity_id, ancestor_id) SELECT object_identity_id, ancestor_id FROM __temp__acl_object_identity_ancestors');
        $this->addSql('DROP TABLE __temp__acl_object_identity_ancestors');
        $this->addSql('CREATE INDEX IDX_825DE2993D9AB4A6 ON acl_object_identity_ancestors (object_identity_id)');
        $this->addSql('CREATE INDEX IDX_825DE299C671CEA1 ON acl_object_identity_ancestors (ancestor_id)');
        $this->addSql('DROP INDEX IDX_46C8B8063D9AB4A6');
        $this->addSql('DROP INDEX IDX_46C8B806DF9183C9');
        $this->addSql('DROP INDEX IDX_46C8B806EA000B10');
        $this->addSql('DROP INDEX IDX_46C8B806EA000B103D9AB4A6DF9183C9');
        $this->addSql('DROP INDEX UNIQ_46C8B806EA000B103D9AB4A64DEF17BCE4289BF4');
        $this->addSql('CREATE TEMPORARY TABLE __temp__acl_entries AS SELECT id, class_id, object_identity_id, security_identity_id, field_name, mask, granting, granting_strategy, audit_success, audit_failure, ace_order FROM acl_entries');
        $this->addSql('DROP TABLE acl_entries');
        $this->addSql('CREATE TABLE acl_entries (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, class_id INTEGER UNSIGNED NOT NULL, object_identity_id INTEGER UNSIGNED DEFAULT NULL, security_identity_id INTEGER UNSIGNED NOT NULL, field_name VARCHAR(50) DEFAULT NULL COLLATE BINARY, mask INTEGER NOT NULL, granting BOOLEAN NOT NULL, granting_strategy VARCHAR(30) NOT NULL COLLATE BINARY, audit_success BOOLEAN NOT NULL, audit_failure BOOLEAN NOT NULL, ace_order SMALLINT UNSIGNED NOT NULL, CONSTRAINT FK_46C8B806EA000B10 FOREIGN KEY (class_id) REFERENCES acl_classes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_46C8B8063D9AB4A6 FOREIGN KEY (object_identity_id) REFERENCES acl_object_identities (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_46C8B806DF9183C9 FOREIGN KEY (security_identity_id) REFERENCES acl_security_identities (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO acl_entries (id, class_id, object_identity_id, security_identity_id, field_name, mask, granting, granting_strategy, audit_success, audit_failure, ace_order) SELECT id, class_id, object_identity_id, security_identity_id, field_name, mask, granting, granting_strategy, audit_success, audit_failure, ace_order FROM __temp__acl_entries');
        $this->addSql('DROP TABLE __temp__acl_entries');
        $this->addSql('CREATE INDEX IDX_46C8B8063D9AB4A6 ON acl_entries (object_identity_id)');
        $this->addSql('CREATE INDEX IDX_46C8B806DF9183C9 ON acl_entries (security_identity_id)');
        $this->addSql('CREATE INDEX IDX_46C8B806EA000B10 ON acl_entries (class_id)');
        $this->addSql('CREATE INDEX IDX_46C8B806EA000B103D9AB4A6DF9183C9 ON acl_entries (class_id, object_identity_id, security_identity_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_46C8B806EA000B103D9AB4A64DEF17BCE4289BF4 ON acl_entries (class_id, object_identity_id, field_name, ace_order)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX UNIQ_46C8B806EA000B103D9AB4A64DEF17BCE4289BF4');
        $this->addSql('DROP INDEX IDX_46C8B806EA000B103D9AB4A6DF9183C9');
        $this->addSql('DROP INDEX IDX_46C8B806EA000B10');
        $this->addSql('DROP INDEX IDX_46C8B8063D9AB4A6');
        $this->addSql('DROP INDEX IDX_46C8B806DF9183C9');
        $this->addSql('CREATE TEMPORARY TABLE __temp__acl_entries AS SELECT id, class_id, object_identity_id, security_identity_id, field_name, ace_order, mask, granting, granting_strategy, audit_success, audit_failure FROM acl_entries');
        $this->addSql('DROP TABLE acl_entries');
        $this->addSql('CREATE TABLE acl_entries (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, class_id INTEGER UNSIGNED NOT NULL, object_identity_id INTEGER UNSIGNED DEFAULT NULL, security_identity_id INTEGER UNSIGNED NOT NULL, field_name VARCHAR(50) DEFAULT NULL, ace_order SMALLINT UNSIGNED NOT NULL, mask INTEGER NOT NULL, granting BOOLEAN NOT NULL, granting_strategy VARCHAR(30) NOT NULL, audit_success BOOLEAN NOT NULL, audit_failure BOOLEAN NOT NULL)');
        $this->addSql('INSERT INTO acl_entries (id, class_id, object_identity_id, security_identity_id, field_name, ace_order, mask, granting, granting_strategy, audit_success, audit_failure) SELECT id, class_id, object_identity_id, security_identity_id, field_name, ace_order, mask, granting, granting_strategy, audit_success, audit_failure FROM __temp__acl_entries');
        $this->addSql('DROP TABLE __temp__acl_entries');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_46C8B806EA000B103D9AB4A64DEF17BCE4289BF4 ON acl_entries (class_id, object_identity_id, field_name, ace_order)');
        $this->addSql('CREATE INDEX IDX_46C8B806EA000B103D9AB4A6DF9183C9 ON acl_entries (class_id, object_identity_id, security_identity_id)');
        $this->addSql('CREATE INDEX IDX_46C8B806EA000B10 ON acl_entries (class_id)');
        $this->addSql('CREATE INDEX IDX_46C8B8063D9AB4A6 ON acl_entries (object_identity_id)');
        $this->addSql('CREATE INDEX IDX_46C8B806DF9183C9 ON acl_entries (security_identity_id)');
        $this->addSql('DROP INDEX UNIQ_9407E5494B12AD6EA000B10');
        $this->addSql('DROP INDEX IDX_9407E54977FA751A');
        $this->addSql('CREATE TEMPORARY TABLE __temp__acl_object_identities AS SELECT id, parent_object_identity_id, class_id, object_identifier, entries_inheriting FROM acl_object_identities');
        $this->addSql('DROP TABLE acl_object_identities');
        $this->addSql('CREATE TABLE acl_object_identities (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, parent_object_identity_id INTEGER UNSIGNED DEFAULT NULL, class_id INTEGER UNSIGNED NOT NULL, object_identifier VARCHAR(100) NOT NULL, entries_inheriting BOOLEAN NOT NULL)');
        $this->addSql('INSERT INTO acl_object_identities (id, parent_object_identity_id, class_id, object_identifier, entries_inheriting) SELECT id, parent_object_identity_id, class_id, object_identifier, entries_inheriting FROM __temp__acl_object_identities');
        $this->addSql('DROP TABLE __temp__acl_object_identities');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9407E5494B12AD6EA000B10 ON acl_object_identities (object_identifier, class_id)');
        $this->addSql('CREATE INDEX IDX_9407E54977FA751A ON acl_object_identities (parent_object_identity_id)');
        $this->addSql('DROP INDEX IDX_825DE2993D9AB4A6');
        $this->addSql('DROP INDEX IDX_825DE299C671CEA1');
        $this->addSql('CREATE TEMPORARY TABLE __temp__acl_object_identity_ancestors AS SELECT object_identity_id, ancestor_id FROM acl_object_identity_ancestors');
        $this->addSql('DROP TABLE acl_object_identity_ancestors');
        $this->addSql('CREATE TABLE acl_object_identity_ancestors (object_identity_id INTEGER UNSIGNED NOT NULL, ancestor_id INTEGER UNSIGNED NOT NULL, PRIMARY KEY(object_identity_id, ancestor_id))');
        $this->addSql('INSERT INTO acl_object_identity_ancestors (object_identity_id, ancestor_id) SELECT object_identity_id, ancestor_id FROM __temp__acl_object_identity_ancestors');
        $this->addSql('DROP TABLE __temp__acl_object_identity_ancestors');
        $this->addSql('CREATE INDEX IDX_825DE2993D9AB4A6 ON acl_object_identity_ancestors (object_identity_id)');
        $this->addSql('CREATE INDEX IDX_825DE299C671CEA1 ON acl_object_identity_ancestors (ancestor_id)');
        $this->addSql('DROP INDEX IDX_ACF41FFEB96B5643');
        $this->addSql('CREATE TEMPORARY TABLE __temp__balance AS SELECT id, portfolio_id, currency, quantity FROM balance');
        $this->addSql('DROP TABLE balance');
        $this->addSql('CREATE TABLE balance (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, portfolio_id INTEGER NOT NULL, currency VARCHAR(3) NOT NULL, quantity DOUBLE PRECISION DEFAULT NULL)');
        $this->addSql('INSERT INTO balance (id, portfolio_id, currency, quantity) SELECT id, portfolio_id, currency, quantity FROM __temp__balance');
        $this->addSql('DROP TABLE __temp__balance');
        $this->addSql('CREATE INDEX IDX_ACF41FFEB96B5643 ON balance (portfolio_id)');
        $this->addSql('DROP INDEX IDX_43629B36727ACA70');
        $this->addSql('DROP INDEX IDX_43629B36E25D857E');
        $this->addSql('DROP INDEX IDX_43629B36EA9FDD75');
        $this->addSql('CREATE TEMPORARY TABLE __temp__classification__category AS SELECT id, parent_id, context, media_id, name, enabled, slug, description, position, created_at, updated_at FROM classification__category');
        $this->addSql('DROP TABLE classification__category');
        $this->addSql('CREATE TABLE classification__category (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, parent_id INTEGER DEFAULT NULL, context INTEGER DEFAULT NULL, media_id INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, position INTEGER DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)');
        $this->addSql('INSERT INTO classification__category (id, parent_id, context, media_id, name, enabled, slug, description, position, created_at, updated_at) SELECT id, parent_id, context, media_id, name, enabled, slug, description, position, created_at, updated_at FROM __temp__classification__category');
        $this->addSql('DROP TABLE __temp__classification__category');
        $this->addSql('CREATE INDEX IDX_43629B36727ACA70 ON classification__category (parent_id)');
        $this->addSql('CREATE INDEX IDX_43629B36E25D857E ON classification__category (context)');
        $this->addSql('CREATE INDEX IDX_43629B36EA9FDD75 ON classification__category (media_id)');
        $this->addSql('DROP INDEX IDX_A406B56AE25D857E');
        $this->addSql('DROP INDEX IDX_A406B56AEA9FDD75');
        $this->addSql('DROP INDEX tag_collection');
        $this->addSql('CREATE TEMPORARY TABLE __temp__classification__collection AS SELECT id, context, media_id, name, enabled, slug, description, created_at, updated_at FROM classification__collection');
        $this->addSql('DROP TABLE classification__collection');
        $this->addSql('CREATE TABLE classification__collection (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, context INTEGER DEFAULT NULL, media_id INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)');
        $this->addSql('INSERT INTO classification__collection (id, context, media_id, name, enabled, slug, description, created_at, updated_at) SELECT id, context, media_id, name, enabled, slug, description, created_at, updated_at FROM __temp__classification__collection');
        $this->addSql('DROP TABLE __temp__classification__collection');
        $this->addSql('CREATE INDEX IDX_A406B56AE25D857E ON classification__collection (context)');
        $this->addSql('CREATE INDEX IDX_A406B56AEA9FDD75 ON classification__collection (media_id)');
        $this->addSql('CREATE UNIQUE INDEX tag_collection ON classification__collection (slug, context)');
        $this->addSql('DROP INDEX IDX_CA57A1C7E25D857E');
        $this->addSql('DROP INDEX tag_context');
        $this->addSql('CREATE TEMPORARY TABLE __temp__classification__tag AS SELECT id, context, name, enabled, slug, created_at, updated_at FROM classification__tag');
        $this->addSql('DROP TABLE classification__tag');
        $this->addSql('CREATE TABLE classification__tag (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, context INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)');
        $this->addSql('INSERT INTO classification__tag (id, context, name, enabled, slug, created_at, updated_at) SELECT id, context, name, enabled, slug, created_at, updated_at FROM __temp__classification__tag');
        $this->addSql('DROP TABLE __temp__classification__tag');
        $this->addSql('CREATE INDEX IDX_CA57A1C7E25D857E ON classification__tag (context)');
        $this->addSql('CREATE UNIQUE INDEX tag_context ON classification__tag (slug, context)');
        $this->addSql('DROP INDEX IDX_FD78D017E2904019');
        $this->addSql('DROP INDEX IDX_FD78D01712469DE2');
        $this->addSql('CREATE TEMPORARY TABLE __temp__comment__comment AS SELECT id, thread_id, category_id, body, ancestors, depth, created_at, state, author_name, email, website, note, private FROM comment__comment');
        $this->addSql('DROP TABLE comment__comment');
        $this->addSql('CREATE TABLE comment__comment (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, thread_id INTEGER DEFAULT NULL, category_id INTEGER DEFAULT NULL, body CLOB NOT NULL, ancestors VARCHAR(1024) NOT NULL, depth INTEGER NOT NULL, created_at DATETIME NOT NULL, state INTEGER NOT NULL, author_name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, note DOUBLE PRECISION DEFAULT NULL, private BOOLEAN DEFAULT NULL)');
        $this->addSql('INSERT INTO comment__comment (id, thread_id, category_id, body, ancestors, depth, created_at, state, author_name, email, website, note, private) SELECT id, thread_id, category_id, body, ancestors, depth, created_at, state, author_name, email, website, note, private FROM __temp__comment__comment');
        $this->addSql('DROP TABLE __temp__comment__comment');
        $this->addSql('CREATE INDEX IDX_FD78D017E2904019 ON comment__comment (thread_id)');
        $this->addSql('CREATE INDEX IDX_FD78D01712469DE2 ON comment__comment (category_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__dividend AS SELECT id, country FROM dividend');
        $this->addSql('DROP TABLE dividend');
        $this->addSql('CREATE TABLE dividend (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, country VARCHAR(2) NOT NULL)');
        $this->addSql('INSERT INTO dividend (id, country) SELECT id, country FROM __temp__dividend');
        $this->addSql('DROP TABLE __temp__dividend');
        $this->addSql('CREATE TEMPORARY TABLE __temp__fee_statement AS SELECT id FROM fee_statement');
        $this->addSql('DROP TABLE fee_statement');
        $this->addSql('CREATE TABLE fee_statement (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)');
        $this->addSql('INSERT INTO fee_statement (id) SELECT id FROM __temp__fee_statement');
        $this->addSql('DROP TABLE __temp__fee_statement');
        $this->addSql('DROP INDEX IDX_B3C77447A76ED395');
        $this->addSql('DROP INDEX IDX_B3C77447FE54D947');
        $this->addSql('CREATE TEMPORARY TABLE __temp__fos_user_user_group AS SELECT user_id, group_id FROM fos_user_user_group');
        $this->addSql('DROP TABLE fos_user_user_group');
        $this->addSql('CREATE TABLE fos_user_user_group (user_id INTEGER NOT NULL, group_id INTEGER NOT NULL, PRIMARY KEY(user_id, group_id))');
        $this->addSql('INSERT INTO fos_user_user_group (user_id, group_id) SELECT user_id, group_id FROM __temp__fos_user_user_group');
        $this->addSql('DROP TABLE __temp__fos_user_user_group');
        $this->addSql('CREATE INDEX IDX_B3C77447A76ED395 ON fos_user_user_group (user_id)');
        $this->addSql('CREATE INDEX IDX_B3C77447FE54D947 ON fos_user_user_group (group_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__interest_statement AS SELECT id FROM interest_statement');
        $this->addSql('DROP TABLE interest_statement');
        $this->addSql('CREATE TABLE interest_statement (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL)');
        $this->addSql('INSERT INTO interest_statement (id) SELECT id FROM __temp__interest_statement');
        $this->addSql('DROP TABLE __temp__interest_statement');
        $this->addSql('DROP INDEX IDX_80D4C5414E7AF8F');
        $this->addSql('DROP INDEX IDX_80D4C541EA9FDD75');
        $this->addSql('CREATE TEMPORARY TABLE __temp__media__gallery_media AS SELECT id, gallery_id, media_id, position, enabled, updated_at, created_at FROM media__gallery_media');
        $this->addSql('DROP TABLE media__gallery_media');
        $this->addSql('CREATE TABLE media__gallery_media (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, gallery_id INTEGER DEFAULT NULL, media_id INTEGER DEFAULT NULL, position INTEGER NOT NULL, enabled BOOLEAN NOT NULL, updated_at DATETIME NOT NULL, created_at DATETIME NOT NULL)');
        $this->addSql('INSERT INTO media__gallery_media (id, gallery_id, media_id, position, enabled, updated_at, created_at) SELECT id, gallery_id, media_id, position, enabled, updated_at, created_at FROM __temp__media__gallery_media');
        $this->addSql('DROP TABLE __temp__media__gallery_media');
        $this->addSql('CREATE INDEX IDX_80D4C5414E7AF8F ON media__gallery_media (gallery_id)');
        $this->addSql('CREATE INDEX IDX_80D4C541EA9FDD75 ON media__gallery_media (media_id)');
        $this->addSql('DROP INDEX IDX_5C6DD74E12469DE2');
        $this->addSql('CREATE TEMPORARY TABLE __temp__media__media AS SELECT id, category_id, name, description, enabled, provider_name, provider_status, provider_reference, provider_metadata, width, height, length, content_type, content_size, copyright, author_name, context, cdn_is_flushable, cdn_flush_identifier, cdn_flush_at, cdn_status, updated_at, created_at FROM media__media');
        $this->addSql('DROP TABLE media__media');
        $this->addSql('CREATE TABLE media__media (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, category_id INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL, description CLOB DEFAULT NULL, enabled BOOLEAN NOT NULL, provider_name VARCHAR(255) NOT NULL, provider_status INTEGER NOT NULL, provider_reference VARCHAR(255) NOT NULL, provider_metadata CLOB DEFAULT NULL --(DC2Type:json)
        , width INTEGER DEFAULT NULL, height INTEGER DEFAULT NULL, length NUMERIC(10, 0) DEFAULT NULL, content_type VARCHAR(255) DEFAULT NULL, content_size INTEGER DEFAULT NULL, copyright VARCHAR(255) DEFAULT NULL, author_name VARCHAR(255) DEFAULT NULL, context VARCHAR(64) DEFAULT NULL, cdn_is_flushable BOOLEAN DEFAULT NULL, cdn_flush_identifier VARCHAR(64) DEFAULT NULL, cdn_flush_at DATETIME DEFAULT NULL, cdn_status INTEGER DEFAULT NULL, updated_at DATETIME NOT NULL, created_at DATETIME NOT NULL)');
        $this->addSql('INSERT INTO media__media (id, category_id, name, description, enabled, provider_name, provider_status, provider_reference, provider_metadata, width, height, length, content_type, content_size, copyright, author_name, context, cdn_is_flushable, cdn_flush_identifier, cdn_flush_at, cdn_status, updated_at, created_at) SELECT id, category_id, name, description, enabled, provider_name, provider_status, provider_reference, provider_metadata, width, height, length, content_type, content_size, copyright, author_name, context, cdn_is_flushable, cdn_flush_identifier, cdn_flush_at, cdn_status, updated_at, created_at FROM __temp__media__media');
        $this->addSql('DROP TABLE __temp__media__media');
        $this->addSql('CREATE INDEX IDX_5C6DD74E12469DE2 ON media__media (category_id)');
        $this->addSql('DROP INDEX IDX_A90210404B89032C');
        $this->addSql('CREATE TEMPORARY TABLE __temp__news__comment AS SELECT id, post_id, name, url, email, message, status, created_at, updated_at FROM news__comment');
        $this->addSql('DROP TABLE news__comment');
        $this->addSql('CREATE TABLE news__comment (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, post_id INTEGER NOT NULL, name VARCHAR(255) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, message CLOB NOT NULL, status INTEGER NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)');
        $this->addSql('INSERT INTO news__comment (id, post_id, name, url, email, message, status, created_at, updated_at) SELECT id, post_id, name, url, email, message, status, created_at, updated_at FROM __temp__news__comment');
        $this->addSql('DROP TABLE __temp__news__comment');
        $this->addSql('CREATE INDEX IDX_A90210404B89032C ON news__comment (post_id)');
        $this->addSql('DROP INDEX IDX_7D109BC83DA5256D');
        $this->addSql('DROP INDEX IDX_7D109BC8F675F31B');
        $this->addSql('DROP INDEX IDX_7D109BC8514956FD');
        $this->addSql('CREATE TEMPORARY TABLE __temp__news__post AS SELECT id, image_id, author_id, collection_id, title, abstract, content, raw_content, content_formatter, enabled, slug, publication_date_start, comments_enabled, comments_close_at, comments_default_status, comments_count, created_at, updated_at FROM news__post');
        $this->addSql('DROP TABLE news__post');
        $this->addSql('CREATE TABLE news__post (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, image_id INTEGER DEFAULT NULL, author_id INTEGER DEFAULT NULL, collection_id INTEGER DEFAULT NULL, title VARCHAR(255) NOT NULL, abstract CLOB NOT NULL, content CLOB NOT NULL, raw_content CLOB NOT NULL, content_formatter VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL, publication_date_start DATETIME DEFAULT NULL, comments_enabled BOOLEAN NOT NULL, comments_close_at DATETIME DEFAULT NULL, comments_default_status INTEGER NOT NULL, comments_count INTEGER DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)');
        $this->addSql('INSERT INTO news__post (id, image_id, author_id, collection_id, title, abstract, content, raw_content, content_formatter, enabled, slug, publication_date_start, comments_enabled, comments_close_at, comments_default_status, comments_count, created_at, updated_at) SELECT id, image_id, author_id, collection_id, title, abstract, content, raw_content, content_formatter, enabled, slug, publication_date_start, comments_enabled, comments_close_at, comments_default_status, comments_count, created_at, updated_at FROM __temp__news__post');
        $this->addSql('DROP TABLE __temp__news__post');
        $this->addSql('CREATE INDEX IDX_7D109BC83DA5256D ON news__post (image_id)');
        $this->addSql('CREATE INDEX IDX_7D109BC8F675F31B ON news__post (author_id)');
        $this->addSql('CREATE INDEX IDX_7D109BC8514956FD ON news__post (collection_id)');
        $this->addSql('DROP INDEX IDX_682B20514B89032C');
        $this->addSql('DROP INDEX IDX_682B2051BAD26311');
        $this->addSql('CREATE TEMPORARY TABLE __temp__news__post_tag AS SELECT post_id, tag_id FROM news__post_tag');
        $this->addSql('DROP TABLE news__post_tag');
        $this->addSql('CREATE TABLE news__post_tag (post_id INTEGER NOT NULL, tag_id INTEGER NOT NULL, PRIMARY KEY(post_id, tag_id))');
        $this->addSql('INSERT INTO news__post_tag (post_id, tag_id) SELECT post_id, tag_id FROM __temp__news__post_tag');
        $this->addSql('DROP TABLE __temp__news__post_tag');
        $this->addSql('CREATE INDEX IDX_682B20514B89032C ON news__post_tag (post_id)');
        $this->addSql('CREATE INDEX IDX_682B2051BAD26311 ON news__post_tag (tag_id)');
        $this->addSql('DROP INDEX IDX_BE94B39E9B6B5FBA');
        $this->addSql('DROP INDEX IDX_BE94B39E2576E0FD');
        $this->addSql('CREATE TEMPORARY TABLE __temp__open_order AS SELECT id, account_id, contract_id, perm_id, client_id, order_id, action_type, total_qty, cash_qty, lmt_price, aux_price, status, remaining_qty FROM open_order');
        $this->addSql('DROP TABLE open_order');
        $this->addSql('CREATE TABLE open_order (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, account_id INTEGER NOT NULL, contract_id INTEGER NOT NULL, perm_id INTEGER NOT NULL, client_id INTEGER NOT NULL, order_id INTEGER NOT NULL, action_type VARCHAR(4) NOT NULL, total_qty DOUBLE PRECISION DEFAULT NULL, cash_qty DOUBLE PRECISION DEFAULT NULL, lmt_price DOUBLE PRECISION DEFAULT NULL, aux_price DOUBLE PRECISION DEFAULT NULL, status VARCHAR(16) NOT NULL, remaining_qty DOUBLE PRECISION NOT NULL)');
        $this->addSql('INSERT INTO open_order (id, account_id, contract_id, perm_id, client_id, order_id, action_type, total_qty, cash_qty, lmt_price, aux_price, status, remaining_qty) SELECT id, account_id, contract_id, perm_id, client_id, order_id, action_type, total_qty, cash_qty, lmt_price, aux_price, status, remaining_qty FROM __temp__open_order');
        $this->addSql('DROP TABLE __temp__open_order');
        $this->addSql('CREATE INDEX IDX_BE94B39E9B6B5FBA ON open_order (account_id)');
        $this->addSql('CREATE INDEX IDX_BE94B39E2576E0FD ON open_order (contract_id)');
        $this->addSql('DROP INDEX IDX_5A8600B0DCD6110');
        $this->addSql('CREATE TEMPORARY TABLE __temp__option AS SELECT id, stock_id, last_trade_date, strike, call_or_put, multiplier, implied_volatility, delta, pv_dividend, gamma, vega, theta FROM option');
        $this->addSql('DROP TABLE option');
        $this->addSql('CREATE TABLE option (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, stock_id INTEGER NOT NULL, last_trade_date DATE NOT NULL, strike DOUBLE PRECISION NOT NULL, call_or_put VARCHAR(1) NOT NULL, multiplier INTEGER NOT NULL, implied_volatility DOUBLE PRECISION DEFAULT NULL, delta DOUBLE PRECISION DEFAULT NULL, pv_dividend DOUBLE PRECISION DEFAULT NULL, gamma DOUBLE PRECISION DEFAULT NULL, vega DOUBLE PRECISION DEFAULT NULL, theta DOUBLE PRECISION DEFAULT NULL)');
        $this->addSql('INSERT INTO option (id, stock_id, last_trade_date, strike, call_or_put, multiplier, implied_volatility, delta, pv_dividend, gamma, vega, theta) SELECT id, stock_id, last_trade_date, strike, call_or_put, multiplier, implied_volatility, delta, pv_dividend, gamma, vega, theta FROM __temp__option');
        $this->addSql('DROP TABLE __temp__option');
        $this->addSql('CREATE INDEX IDX_5A8600B0DCD6110 ON option (stock_id)');
        $this->addSql('DROP INDEX IDX_66F58DA0727ACA70');
        $this->addSql('DROP INDEX IDX_66F58DA0C4663E4');
        $this->addSql('CREATE TEMPORARY TABLE __temp__page__block AS SELECT id, parent_id, page_id, name, type, settings, enabled, position, created_at, updated_at FROM page__block');
        $this->addSql('DROP TABLE page__block');
        $this->addSql('CREATE TABLE page__block (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, parent_id INTEGER DEFAULT NULL, page_id INTEGER DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, type VARCHAR(255) NOT NULL, settings CLOB NOT NULL --(DC2Type:json)
        , enabled BOOLEAN DEFAULT NULL, position INTEGER DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)');
        $this->addSql('INSERT INTO page__block (id, parent_id, page_id, name, type, settings, enabled, position, created_at, updated_at) SELECT id, parent_id, page_id, name, type, settings, enabled, position, created_at, updated_at FROM __temp__page__block');
        $this->addSql('DROP TABLE __temp__page__block');
        $this->addSql('CREATE INDEX IDX_66F58DA0727ACA70 ON page__block (parent_id)');
        $this->addSql('CREATE INDEX IDX_66F58DA0C4663E4 ON page__block (page_id)');
        $this->addSql('DROP INDEX IDX_2FAE39EDF6BD1646');
        $this->addSql('DROP INDEX IDX_2FAE39ED727ACA70');
        $this->addSql('DROP INDEX IDX_2FAE39ED158E0B66');
        $this->addSql('CREATE TEMPORARY TABLE __temp__page__page AS SELECT id, site_id, parent_id, target_id, route_name, page_alias, type, position, enabled, decorate, edited, name, slug, url, custom_url, request_method, title, meta_keyword, meta_description, javascript, stylesheet, raw_headers, template, created_at, updated_at FROM page__page');
        $this->addSql('DROP TABLE page__page');
        $this->addSql('CREATE TABLE page__page (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, site_id INTEGER DEFAULT NULL, parent_id INTEGER DEFAULT NULL, target_id INTEGER DEFAULT NULL, route_name VARCHAR(255) NOT NULL, page_alias VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, position INTEGER NOT NULL, enabled BOOLEAN NOT NULL, decorate BOOLEAN NOT NULL, edited BOOLEAN NOT NULL, name VARCHAR(255) NOT NULL, slug CLOB DEFAULT NULL, url CLOB DEFAULT NULL, custom_url CLOB DEFAULT NULL, request_method VARCHAR(255) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, meta_keyword VARCHAR(255) DEFAULT NULL, meta_description VARCHAR(255) DEFAULT NULL, javascript CLOB DEFAULT NULL, stylesheet CLOB DEFAULT NULL, raw_headers CLOB DEFAULT NULL, template VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)');
        $this->addSql('INSERT INTO page__page (id, site_id, parent_id, target_id, route_name, page_alias, type, position, enabled, decorate, edited, name, slug, url, custom_url, request_method, title, meta_keyword, meta_description, javascript, stylesheet, raw_headers, template, created_at, updated_at) SELECT id, site_id, parent_id, target_id, route_name, page_alias, type, position, enabled, decorate, edited, name, slug, url, custom_url, request_method, title, meta_keyword, meta_description, javascript, stylesheet, raw_headers, template, created_at, updated_at FROM __temp__page__page');
        $this->addSql('DROP TABLE __temp__page__page');
        $this->addSql('CREATE INDEX IDX_2FAE39EDF6BD1646 ON page__page (site_id)');
        $this->addSql('CREATE INDEX IDX_2FAE39ED727ACA70 ON page__page (parent_id)');
        $this->addSql('CREATE INDEX IDX_2FAE39ED158E0B66 ON page__page (target_id)');
        $this->addSql('DROP INDEX IDX_3963EF9AF6BD1646');
        $this->addSql('DROP INDEX IDX_3963EF9AC4663E4');
        $this->addSql('DROP INDEX idx_snapshot_dates_enabled');
        $this->addSql('CREATE TEMPORARY TABLE __temp__page__snapshot AS SELECT id, site_id, page_id, route_name, page_alias, type, position, enabled, decorate, name, url, parent_id, target_id, content, publication_date_start, publication_date_end, created_at, updated_at FROM page__snapshot');
        $this->addSql('DROP TABLE page__snapshot');
        $this->addSql('CREATE TABLE page__snapshot (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, site_id INTEGER DEFAULT NULL, page_id INTEGER DEFAULT NULL, route_name VARCHAR(255) NOT NULL, page_alias VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, position INTEGER NOT NULL, enabled BOOLEAN NOT NULL, decorate BOOLEAN NOT NULL, name VARCHAR(255) NOT NULL, url CLOB DEFAULT NULL, parent_id INTEGER DEFAULT NULL, target_id INTEGER DEFAULT NULL, content CLOB DEFAULT NULL --(DC2Type:json)
        , publication_date_start DATETIME DEFAULT NULL, publication_date_end DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)');
        $this->addSql('INSERT INTO page__snapshot (id, site_id, page_id, route_name, page_alias, type, position, enabled, decorate, name, url, parent_id, target_id, content, publication_date_start, publication_date_end, created_at, updated_at) SELECT id, site_id, page_id, route_name, page_alias, type, position, enabled, decorate, name, url, parent_id, target_id, content, publication_date_start, publication_date_end, created_at, updated_at FROM __temp__page__snapshot');
        $this->addSql('DROP TABLE __temp__page__snapshot');
        $this->addSql('CREATE INDEX IDX_3963EF9AF6BD1646 ON page__snapshot (site_id)');
        $this->addSql('CREATE INDEX IDX_3963EF9AC4663E4 ON page__snapshot (page_id)');
        $this->addSql('CREATE INDEX idx_snapshot_dates_enabled ON page__snapshot (publication_date_start, publication_date_end, enabled)');
        $this->addSql('DROP INDEX IDX_A9ED10627E3C61F9');
        $this->addSql('DROP INDEX IDX_A9ED1062E80D127B');
        $this->addSql('CREATE TEMPORARY TABLE __temp__portfolio AS SELECT id, owner_id, benchmark_id, account, base_currency, name, put_ratio, sell_naked_put_sleep, find_symbols_sleep FROM portfolio');
        $this->addSql('DROP TABLE portfolio');
        $this->addSql('CREATE TABLE portfolio (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, owner_id INTEGER DEFAULT NULL, benchmark_id INTEGER DEFAULT NULL, account VARCHAR(31) NOT NULL, base_currency VARCHAR(3) NOT NULL, name VARCHAR(32) DEFAULT NULL, put_ratio DOUBLE PRECISION DEFAULT NULL, sell_naked_put_sleep SMALLINT DEFAULT NULL, find_symbols_sleep SMALLINT DEFAULT NULL)');
        $this->addSql('INSERT INTO portfolio (id, owner_id, benchmark_id, account, base_currency, name, put_ratio, sell_naked_put_sleep, find_symbols_sleep) SELECT id, owner_id, benchmark_id, account, base_currency, name, put_ratio, sell_naked_put_sleep, find_symbols_sleep FROM __temp__portfolio');
        $this->addSql('DROP TABLE __temp__portfolio');
        $this->addSql('CREATE INDEX IDX_A9ED10627E3C61F9 ON portfolio (owner_id)');
        $this->addSql('CREATE INDEX IDX_A9ED1062E80D127B ON portfolio (benchmark_id)');
        $this->addSql('DROP INDEX IDX_462CE4F5B96B5643');
        $this->addSql('DROP INDEX IDX_462CE4F52576E0FD');
        $this->addSql('CREATE TEMPORARY TABLE __temp__position AS SELECT id, portfolio_id, contract_id, open_date, quantity, cost FROM position');
        $this->addSql('DROP TABLE position');
        $this->addSql('CREATE TABLE position (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, portfolio_id INTEGER DEFAULT NULL, contract_id INTEGER NOT NULL, open_date DATE NOT NULL, quantity DOUBLE PRECISION NOT NULL, cost DOUBLE PRECISION DEFAULT NULL)');
        $this->addSql('INSERT INTO position (id, portfolio_id, contract_id, open_date, quantity, cost) SELECT id, portfolio_id, contract_id, open_date, quantity, cost FROM __temp__position');
        $this->addSql('DROP TABLE __temp__position');
        $this->addSql('CREATE INDEX IDX_462CE4F5B96B5643 ON position (portfolio_id)');
        $this->addSql('CREATE INDEX IDX_462CE4F52576E0FD ON position (contract_id)');
        $this->addSql('DROP INDEX IDX_C0DB5176B96B5643');
        $this->addSql('DROP INDEX IDX_C0DB5176DCD6110');
        $this->addSql('DROP INDEX IDX_C0DB5176B3D28FB');
        $this->addSql('CREATE TEMPORARY TABLE __temp__statement AS SELECT id, portfolio_id, stock_id, trade_unit_id, date, currency, amount, description, trade_id, fx_rate_to_base, statement_type FROM statement');
        $this->addSql('DROP TABLE statement');
        $this->addSql('CREATE TABLE statement (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, portfolio_id INTEGER NOT NULL, stock_id INTEGER DEFAULT NULL, trade_unit_id INTEGER DEFAULT NULL, date DATETIME NOT NULL, currency VARCHAR(3) NOT NULL, amount DOUBLE PRECISION NOT NULL, description VARCHAR(64) DEFAULT NULL, trade_id INTEGER DEFAULT NULL, fx_rate_to_base DOUBLE PRECISION DEFAULT NULL, statement_type VARCHAR(4) NOT NULL)');
        $this->addSql('INSERT INTO statement (id, portfolio_id, stock_id, trade_unit_id, date, currency, amount, description, trade_id, fx_rate_to_base, statement_type) SELECT id, portfolio_id, stock_id, trade_unit_id, date, currency, amount, description, trade_id, fx_rate_to_base, statement_type FROM __temp__statement');
        $this->addSql('DROP TABLE __temp__statement');
        $this->addSql('CREATE INDEX IDX_C0DB5176B96B5643 ON statement (portfolio_id)');
        $this->addSql('CREATE INDEX IDX_C0DB5176DCD6110 ON statement (stock_id)');
        $this->addSql('CREATE INDEX IDX_C0DB5176B3D28FB ON statement (trade_unit_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__stock AS SELECT id, dividend_ttm, eps_ttm, eps_forward, description, industry, category, subcategory, historical_volatility FROM stock');
        $this->addSql('DROP TABLE stock');
        $this->addSql('CREATE TABLE stock (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, dividend_ttm DOUBLE PRECISION DEFAULT NULL, eps_ttm DOUBLE PRECISION DEFAULT NULL, eps_forward DOUBLE PRECISION DEFAULT NULL, description VARCHAR(31) DEFAULT NULL, industry VARCHAR(32) DEFAULT NULL, category VARCHAR(32) DEFAULT NULL, subcategory VARCHAR(40) DEFAULT NULL, historical_volatility DOUBLE PRECISION DEFAULT NULL)');
        $this->addSql('INSERT INTO stock (id, dividend_ttm, eps_ttm, eps_forward, description, industry, category, subcategory, historical_volatility) SELECT id, dividend_ttm, eps_ttm, eps_forward, description, industry, category, subcategory, historical_volatility FROM __temp__stock');
        $this->addSql('DROP TABLE __temp__stock');
        $this->addSql('CREATE TEMPORARY TABLE __temp__tax AS SELECT id, country FROM tax');
        $this->addSql('DROP TABLE tax');
        $this->addSql('CREATE TABLE tax (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, country VARCHAR(2) NOT NULL)');
        $this->addSql('INSERT INTO tax (id, country) SELECT id, country FROM __temp__tax');
        $this->addSql('DROP TABLE __temp__tax');
        $this->addSql('CREATE TEMPORARY TABLE __temp__trade AS SELECT id, quantity, price, proceeds, fees, realized_pnl, status FROM trade');
        $this->addSql('DROP TABLE trade');
        $this->addSql('CREATE TABLE trade (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, quantity DOUBLE PRECISION NOT NULL, price DOUBLE PRECISION NOT NULL, proceeds DOUBLE PRECISION DEFAULT NULL, fees DOUBLE PRECISION DEFAULT NULL, realized_pnl DOUBLE PRECISION DEFAULT NULL, status SMALLINT NOT NULL)');
        $this->addSql('INSERT INTO trade (id, quantity, price, proceeds, fees, realized_pnl, status) SELECT id, quantity, price, proceeds, fees, realized_pnl, status FROM __temp__trade');
        $this->addSql('DROP TABLE __temp__trade');
        $this->addSql('DROP INDEX IDX_63AFBEA22576E0FD');
        $this->addSql('CREATE TEMPORARY TABLE __temp__trade_option AS SELECT id, contract_id, quantity, price, proceeds, fees, realized_pnl, status FROM trade_option');
        $this->addSql('DROP TABLE trade_option');
        $this->addSql('CREATE TABLE trade_option (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, contract_id INTEGER NOT NULL, quantity DOUBLE PRECISION NOT NULL, price DOUBLE PRECISION NOT NULL, proceeds DOUBLE PRECISION DEFAULT NULL, fees DOUBLE PRECISION DEFAULT NULL, realized_pnl DOUBLE PRECISION DEFAULT NULL, status SMALLINT NOT NULL)');
        $this->addSql('INSERT INTO trade_option (id, contract_id, quantity, price, proceeds, fees, realized_pnl, status) SELECT id, contract_id, quantity, price, proceeds, fees, realized_pnl, status FROM __temp__trade_option');
        $this->addSql('DROP TABLE __temp__trade_option');
        $this->addSql('CREATE INDEX IDX_63AFBEA22576E0FD ON trade_option (contract_id)');
        $this->addSql('DROP INDEX IDX_BE407BA8C0F75674');
        $this->addSql('DROP INDEX IDX_BE407BA8B96B5643');
        $this->addSql('CREATE TEMPORARY TABLE __temp__trade_unit AS SELECT id, symbol_id, portfolio_id, strategy, opening_date, closing_date, status, pn_l, currency, risk, comment FROM trade_unit');
        $this->addSql('DROP TABLE trade_unit');
        $this->addSql('CREATE TABLE trade_unit (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, symbol_id INTEGER NOT NULL, portfolio_id INTEGER DEFAULT NULL, strategy SMALLINT NOT NULL, opening_date DATETIME DEFAULT NULL, closing_date DATETIME DEFAULT NULL, status SMALLINT NOT NULL, pn_l DOUBLE PRECISION DEFAULT NULL, currency VARCHAR(3) DEFAULT NULL, risk INTEGER DEFAULT NULL, comment VARCHAR(255) DEFAULT NULL)');
        $this->addSql('INSERT INTO trade_unit (id, symbol_id, portfolio_id, strategy, opening_date, closing_date, status, pn_l, currency, risk, comment) SELECT id, symbol_id, portfolio_id, strategy, opening_date, closing_date, status, pn_l, currency, risk, comment FROM __temp__trade_unit');
        $this->addSql('DROP TABLE __temp__trade_unit');
        $this->addSql('CREATE INDEX IDX_BE407BA8C0F75674 ON trade_unit (symbol_id)');
        $this->addSql('CREATE INDEX IDX_BE407BA8B96B5643 ON trade_unit (portfolio_id)');
        $this->addSql('DROP INDEX IDX_CE33C44BDCD6110');
        $this->addSql('DROP INDEX IDX_CE33C44BB96B5643');
        $this->addSql('CREATE TEMPORARY TABLE __temp__trading_parameters AS SELECT id, stock_id, portfolio_id, nav_ratio FROM trading_parameters');
        $this->addSql('DROP TABLE trading_parameters');
        $this->addSql('CREATE TABLE trading_parameters (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, stock_id INTEGER NOT NULL, portfolio_id INTEGER NOT NULL, nav_ratio DOUBLE PRECISION NOT NULL)');
        $this->addSql('INSERT INTO trading_parameters (id, stock_id, portfolio_id, nav_ratio) SELECT id, stock_id, portfolio_id, nav_ratio FROM __temp__trading_parameters');
        $this->addSql('DROP TABLE __temp__trading_parameters');
        $this->addSql('CREATE INDEX IDX_CE33C44BDCD6110 ON trading_parameters (stock_id)');
        $this->addSql('CREATE INDEX IDX_CE33C44BB96B5643 ON trading_parameters (portfolio_id)');
    }
}
